# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      seed: magnet:?xt=urn:btih:71b3a19286e76e000e6ff7f8b84cba01a809029f&dn=[javdb.com]PRED-386
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v2
      - run: echo $seed

      # Runs a single command using the runners shell
      - name:  Install package
        run: sudo snap install aria2c
        
      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}

      # Runs a set of commands using the runners shell
      - name: show Aria2c info
        run: |
          aria2c -v
          
      - run: rclone copy --progress phys://aria/dht.dat .
          
      - name: dl
        run: |
          aria2c  --seed-time=0  --dht-file-path=dht.dat "$seed"
          
      - run: rclone copy --progress . phys://aria_result
