# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  repository_dispatch:
    types: [backend_automation]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  
  from_dl:
    if: github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest
    env:
      time: 5.5h
    steps:
      - run: echo "seed:" "${{ github.event.client_payload.seed }}"
 
      - name:  Install package
        run: sudo snap install aria2c
        
      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}

      # Runs a set of commands using the runners shell
      - name: show Aria2c info
        run: |
          aria2c -v
          
      - run: rclone copy --progress phys://aria/dht.dat .
          
      - name: dl
        run: |
          timeout --preserve-status ${{env.time}} aria2c  --seed-time=0 -c --dht-file-path=dht.dat "${{ github.event.client_payload.seed }}"
          
      - name: ul
        if: success()
        run: rclone copy  --drive-upload-cutoff 1000T  --progress . phys://aria_result
      
  build:
    #if: github.event_name == 'closed'
    if: github.event_name != 'repository_dispatch'
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      seed: magnet:?xt=urn:btih:e7d1abae2d1707f19e566e776dfc1a63d2d0ce45&dn=debian-11.1.0-amd64-netinst.iso
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v2
      - run: echo $seed

      # Prepare buckets

      # Runs a single command using the runners shell
      - name:  Install package
        run: sudo snap install aria2c
        
      # Runs a set of commands using the runners shell
      - name: show Aria2c info
        run: |
          aria2c -v
          
      - run: rclone copy --progress phys://aria/dht.dat .
          
      - name: dl
        run: |
          aria2c  --seed-time=0  -c --dht-file-path=dht.dat "$seed"
          
      - name: Upload file to bucket
        if: success()
        uses: zdurham/s3-upload-github-action@master
        env:
          FILE: "*"
          AWS_REGION: 'us-east-1'
          S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          S3_KEY: ${{ secrets.S3_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  lab: 
    runs-on: ubuntu-latest
    steps:
      - uses: derekn/s5cmd-action@v1
        with:
          version: 2.1.0-beta.1
      - name: Init
        run: |
          echo ${{secrets.INIT}} | base64 -d > init.cred
          # source ./init.cred
          # echo $aws_access_key_id
          # echo $aws_secret_access_key
          cat init.cred
          # s5cmd --credentials-file init.cred --endpoint-url https://s3.us-west-004.backblazeb2.com/ ls s3://aria-config
          s5cmd --credentials-file init.cred --endpoint-url ${{ secrets.S3_ENDPOINT_URL }} ls s3://aria-config



